### ISSUE TITLE
Dev Meetings - 04/07/2017

### ISSUE THREAD

**Issue by Bucknalla** [WarwickTECH/meetings#1]
# Dev Meeting 04/07/2017

### Agenda

- [x] Decide on strategy for: 
    - [x] Job Board
    - [x] Resource Hub
    - [x] Coding Courses (WarwickCoding)
- [x] Implement Task & File Management Systems (Trello, Asana, Etc.)
- [x] Build v1.0.0 of the new Website
- [x] Discuss team structure and how to distribute load
- [x] Discuss/Decide on internal resource hosting (owncloud?)

### Partipants -

- @bucknalla (Alex Bucknall)
- @PiR-P (Pierre Pasquet)

**Comment by Bucknalla** [comment]
# Notes
### Job Board
- .yml files
- build from gitpages
### Resource Hub
- Scopes for user (owncloud)
- Generalised user login
- OAuth2
### Coding Warwick
- Excel/VBA
- Web (HTML/CSS -> JS/Node)
- Python
- Git Classroom
    - Mark Assignments
- Find teacher
### Task & File Management
- Trello (Non-Tech)
    - Trello Speaker @bucknalla
- GitHub (Dev)
    - GitHub Speaker (Joe) @bucknalla
### Website
- @PiR-P to get mock up designs
- .yml for events
### Team Structure
- Ok for now, reasses in week 5 term 1
### Internal Resource
- @PiR-P to look into server cost/hosting
